### ISSUE TITLE
Skipped tests leads to empty test run creation

### ISSUE THREAD

**Issue by mnataraj17** [JSanchezIO/JSanchezIO#2]
Hi
I use playwright for my automation tests. It creates an XML report and if some of the tests are skipped, the status of that particular test is highlighted with status "Untested" in the XML. 
WhenI try to upload any xml which contains few tests with status as "Untested", it's created test runs on testrail with no pass/fail status for any of the tests inside it.
Below is the exception I get when I try to upload the results
![Screen Shot 2023-03-29 at 4 11 54 PM](https://user-images.githubusercontent.com/92099129/228656185-2a1d5108-8516-4302-8e89-87c06bfe957c.png)

**Comment by JSanchezIO** [comment]
Can you provide an XML so I can test locally as I work through this? Feel free to redact any sensitive information.

**Comment by mnataraj17** [comment]
Here you go!
This sample report contains one skipped test and 1 passed test.
[results.txt](https://github.com/JSanchezIO/JSanchezIO/files/11121874/results.txt)
(Note: Sending it as txt file since xml file type not allowed here. Please change the extension before using)

**Comment by JSanchezIO** [comment]
This should be solved in v1.5.1

**Comment by mnataraj17** [comment]
@JSanchezIO
Thanks for working on this. In the latest version, it's not creating empty run but skipped tests are marked as "Passed" instead of "untested" status. 
Should I create a new issue this?
