### ISSUE TITLE
Can we get an option to input milestone ID as well for the test run?

### ISSUE THREAD

**Issue by mnataraj17** [JSanchezIO/JSanchezIO#3]
Hi
We are trying to generate a report from Testrail which showcase the trend of testcase results(from test runs created using junit-testrail-reporter) over a period of time considering all the test runs in a milestone. 
It would be great help, if we have an option mention milestone id as input and it tags test runs created to a milestone we input.
Thanks!

**Comment by JSanchezIO** [comment]
Sounds like a great feature. I'd like to understand the usage a bit more before adding it. Is it likely that tests would be under different milestones, or that the whole report should be classified under the same milestone?

**Comment by mnataraj17** [comment]
We want to generate a summary report for the test runs created every 15 days which shows the trend of testcase count , passed, failed scenarios. In order to generate it on Testrail, they need to be grouped under single milestone. Right now, we test runs created are not tagged with any milestones. 
If we can get an option to do that. I can just choose all the test runs under single milestone and try to generate a summary report.

**Comment by JSanchezIO** [comment]
This has been released in v1.5.0
